version: "3"
services:
   node:
        build: docker/node
        image: node-builder
        working_dir: /src
        command: sh -c "cd valurap-ui && yarn serve"
        ports:
                - 8080:8080
        volumes:
                - .:/src
        restart: always
